### PR TITLE
Config files should be owned by root, not apache

### PR DESCRIPTION
**Pull request by ekohl**
This fixes https://github.com/hunner/puppetlabs-apache/issues/15.

### CODE REVIEW

**Comment by hunner** [comment]
Thanks for this PR @ekohl ! Before merging, I just wanted to double-check that the spec tests have been updated to reflect the root ownership? Thanks!

**Comment by ekohl** [comment]
@hunner there are no spec tests to check it yet, but I'm willing to add them. Playing with spec tests has been on my todo list anyway.

**Comment by ekohl** [comment]
@hunner this should do it.

**Comment by hunner** [comment]
Thanks!

**Pull request merged**
