### PR TITLE
Custom logging for apache::vhost

### PR DESCRIPTION
**Pull request by trlinkin**
This patch adds the ability to change how vhost logging works. This patch
adds new parameters to 'apache::vhost' define type. This allows users to
specify a log format or nickname for the 'CustomLog' directive. This also
allows users to specify a pipe as the destination for the 'ErrorLog' and
'CustomLog' directives.

### CODE REVIEW

**Comment by hunner** [comment]
Could we get specs and documentation updated for this PR? Would you like to do it, or shall I?

**Comment by trlinkin** [comment]
I've got it. I'll do it this weekend.

**Comment by trlinkin** [comment]
@hunner We're good to go here I believe.

**Comment by trlinkin** [comment]
Opened pull on puppetlabs/puppetlabs-apache master.

**Pull request closed without merging**
